Check for useless inherited timing points
Naxesss/MapsetChecks pull request #2
Opened 2019-11-22 00:29 UTC by cl8n

2019-11-22 23:58 UTC, Naxesss requested changes
Should be good to go after this. Have confirmed it works. It still considers inherited lines with no objects after them used (similarly only modifying SV but not having sliders), but I can add that part after merging.

2019-11-22 23:58 UTC, Naxesss commented on checks/all modes/timing/CheckUnusedLines.cs
> +                    mapper may have intended to use these timing points for something, but forgot to change their settings."
Should be a separate paragraph since it's no longer about uninherited lines.

Would rather use something like this instead:
"Unused inherited lines don't cause any issues and are basically equivalent to bookmarks. Unless the mapper intended to do something with them (e.g. silencing slider ends/ticks), they can be safely removed, but removal is not necessary."

With the way it's written currently, the paragraph implies they should be changed because "there's no reason to keep them around", which is odd considering there's usually no reason to remove them either. It does improve file size by a few bytes, but I don't think it's a good idea to encourage micro-optimization.

2019-11-22 23:58 UTC, Naxesss commented on checks/all modes/timing/CheckUnusedLines.cs
> +                    new IssueTemplate(Issue.Level.Problem,
Problems are reserved for issues that almost certinaly must be fixed (e.g. unrankables and game-breaking glitches). I'd at most make this a minor issue, anything else would be too intrusive for what it's worth.

2019-11-22 23:58 UTC, Naxesss commented on checks/all modes/timing/CheckUnusedLines.cs
> +                if (!(allLines[i] is InheritedLine currentLine)) continue;
Put continue on the next line for consistency, see [line 111](https://github.com/Naxesss/MapsetChecks/blob/master/checks/all%20modes/timing/CheckUnusedLines.cs#L111).

2019-11-22 23:58 UTC, Naxesss commented on checks/all modes/timing/CheckUnusedLines.cs
> +
Remove the new line for consistency, see [line 81](https://github.com/Naxesss/MapsetChecks/blob/master/checks/all%20modes/timing/CheckUnusedLines.cs#L81).

2019-11-22 23:58 UTC, Naxesss commented on checks/all modes/timing/CheckUnusedLines.cs
> +                        "{0} Changes nothing.",
```suggestion
                        "{0} Inherited line changes nothing.",
```
Otherwise ambiguous for timestamps with both uninherited and inherited lines present.

Should also prepend "Uninherited line" for the other templates now that the issue message is simply "timing line" and not "uninherited line".

2019-11-22 23:58 UTC, Naxesss commented on checks/all modes/timing/CheckUnusedLines.cs
> +                    currentLine.omitsBarLine == previousLine.omitsBarLine)
Was about to say `omitsBarLine` works in a different way to other properties and isn't properly handled here, but apparently it's unused for inherited lines (just tested), so you can just remove this comparison.

2019-11-23 00:53 UTC, cl8n commented on checks/all modes/timing/CheckUnusedLines.cs
> +                    mapper may have intended to use these timing points for something, but forgot to change their settings."
dont rly agree with the precedent but thisis ur program so Ok

2019-11-23 01:32 UTC, merged